---
- name: add the mesosphere repo (el7)
  yum: >
    state=present
    name='http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm'
  when: ansible_distribution_major_version == "7"
  environment: '{{proxy_env}}'

- name: add the mesosphere repo (el6)
  yum: >
    state=present
    name='http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm'
  when: ansible_distribution_major_version == "6" or ansible_distribution == "Amazon"
  environment: '{{proxy_env}}'

- name: mkdir /etc/mesos
  file: >
    owner="root"
    group="root"
    mode="go-w"
    path=/etc/mesos
    state=directory
  
- name: install /etc/mesos/zk
  template: >
    src=etc/mesos/zk.j2
    dest=/etc/mesos/zk
    owner=root
    group=root
    mode=0644

